server.port=8085
spring.application.name=api-gateway
spring.output.ansi.enabled=ALWAYS

# Route 1: Countries (Filtre nettoyé / supprimé si inutile)
spring.cloud.gateway.routes[0].id=country-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/countries/**

# Route 2: Cities
spring.cloud.gateway.routes[1].id=city-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/cities/**

# Route 3: Relation Country-Cities
spring.cloud.gateway.routes[2].id=country-cities
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/countries/*/cities/**

# Configuration des Timeouts (Évite que le Gateway reste bloqué)
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s