server.port=8085

# =========================
# ROUTES DOCKER (service discovery)
# =========================

# API endpoints - proxy to service
spring.cloud.gateway.routes[0].id=country-service
spring.cloud.gateway.routes[0].uri=http://country-city-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/countries/**

# Cities endpoint - proxy to service
spring.cloud.gateway.routes[1].id=city-service
spring.cloud.gateway.routes[1].uri=http://country-city-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/cities/**

# Country-Cities endpoint
spring.cloud.gateway.routes[2].id=country-cities
spring.cloud.gateway.routes[2].uri=http://country-city-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/countries/*/cities/**

# Actuator
spring.cloud.gateway.routes[3].id=actuator
spring.cloud.gateway.routes[3].uri=http://country-city-service:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/actuator/**

# Timeouts
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s

spring.cloud.gateway.forwarded.enabled=false

# Route pour l'interface de Swagger et ses fichiers (JS, CSS, Images)
spring.cloud.gateway.routes[4].id=swagger-resources
spring.cloud.gateway.routes[4].uri=http://country-city-service:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/swagger-ui/**

# Route pour la documentation OpenAPI (le JSON qui contient vos API)
spring.cloud.gateway.routes[5].id=openapi-docs
spring.cloud.gateway.routes[5].uri=http://country-city-service:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/v3/api-docs/**

# Route pour les webjars (les dépendances UI internes de Swagger)
spring.cloud.gateway.routes[6].id=swagger-webjars
spring.cloud.gateway.routes[6].uri=http://country-city-service:8081
spring.cloud.gateway.routes[6].predicates[0]=Path=/webjars/**

# Oauth
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/country-system/protocol/openid-connect/certs

# Actuator Prometheus
management.endpoints.web.exposure.include=prometheus,health,metrics
management.metrics.export.prometheus.enabled=true
