server.port=8085

# =========================
# ROUTES DOCKER (service discovery)
# =========================

spring.cloud.gateway.routes[0].id=country-service
spring.cloud.gateway.routes[0].uri=http://country-city-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/countries/**

spring.cloud.gateway.routes[1].id=city-service
spring.cloud.gateway.routes[1].uri=http://country-city-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/cities/**

spring.cloud.gateway.routes[2].id=country-cities
spring.cloud.gateway.routes[2].uri=http://country-city-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/countries/*/cities/**

spring.cloud.gateway.routes[3].id=swagger-ui
spring.cloud.gateway.routes[3].uri=http://country-city-service:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/swagger-ui/**

spring.cloud.gateway.routes[4].id=api-docs
spring.cloud.gateway.routes[4].uri=http://country-city-service:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/v3/api-docs/**

spring.cloud.gateway.routes[5].id=actuator
spring.cloud.gateway.routes[5].uri=http://country-city-service:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/actuator/**

spring.cloud.gateway.routes[6].id=swagger-ui
spring.cloud.gateway.routes[6].uri=http://country-city-service:8081
spring.cloud.gateway.routes[6].predicates[0]=Path=/swagger-ui/**

spring.cloud.gateway.routes[7].id=swagger-ui-html
spring.cloud.gateway.routes[7].uri=http://country-city-service:8081
spring.cloud.gateway.routes[7].predicates[0]=Path=/swagger-ui.html

spring.cloud.gateway.routes[8].id=api-docs
spring.cloud.gateway.routes[8].uri=http://country-city-service:8081
spring.cloud.gateway.routes[8].predicates[0]=Path=/v3/api-docs/**

# Timeouts
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s

# Oauth
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/country-system

# Springdoc OpenAPI / Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
