server.port=8085

# =========================
# ROUTES DEV (LOCALHOST)
# =========================

spring.cloud.gateway.routes[0].id=country-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/countries/**

spring.cloud.gateway.routes[1].id=city-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/cities/**

spring.cloud.gateway.routes[2].id=country-cities
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/countries/*/cities/**

spring.cloud.gateway.routes[3].id=swagger-ui
spring.cloud.gateway.routes[3].uri=http://localhost:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/swagger-ui/**

spring.cloud.gateway.routes[4].id=api-docs
spring.cloud.gateway.routes[4].uri=http://localhost:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/v3/api-docs/**

spring.cloud.gateway.routes[5].id=actuator
spring.cloud.gateway.routes[5].uri=http://localhost:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/actuator/**

# Timeouts DEV
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s