server.port=8085
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=country-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/countries/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/countries/(?<segment>.*), /countries/${segment}

spring.cloud.gateway.routes[1].id=city-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/cities/**

spring.cloud.gateway.routes[2].id=country-cities
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/countries/*/cities/**