server.port=8081

# PostgreSQL Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/countrydb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Docker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Oauth
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/country-system/protocol/openid-connect/certs


# ====================================================================
# CONFIGURATION SWAGGER / OPENAPI (Pour l'affichage via la Gateway)
# ====================================================================

# 1. Force Swagger à envoyer les requêtes d'API à la Gateway (Règle le Failed to fetch)
springdoc.openapi.servers[0].url=http://localhost:8085
springdoc.openapi.servers[0].description=API Gateway

# 2. Configure le bouton Authorize avec le flux Client Credentials
springdoc.openapi.components.security-schemes.keycloak-auth.type=oauth2
springdoc.openapi.components.security-schemes.keycloak-auth.description=Authentification Client Credentials (Machine-to-Machine)
springdoc.openapi.components.security-schemes.keycloak-auth.flows.clientCredentials.tokenUrl=http://localhost:8080/realms/country-system/protocol/openid-connect/token

# 3. Applique automatiquement le cadenas de sécurité sur TOUS vos endpoints dans l'IHM
springdoc.openapi.security[0].keycloak-auth[0]=openid